name: Run clang-format Linter

on:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  format_code:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - uses: actions/checkout@v4
    - uses: DoozyX/clang-format-lint-action@v0.18.1
      with:
        source: 'include examples test tools'
        extensions: 'hpp,cpp,ipp,h,c'
        clangFormatVersion: 14
        inplace: True
        style: file
    - name: Check for changes from formatting
      run: |
        UNFORMATTED_FILES=$(git diff --name-only HEAD)
        if [ "${UNFORMATTED_FILES}" != '' ]; then
          PASS=0
        else
          PASS=1
        fi
    - uses: marocchino/sticky-pull-request-comment@v2
      with:
        message: |
          This PR has unformatted changes in the following files:
