name: Run clang-format Linter

on: [push]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.18.1
      with:
        source: 'include examples test tools'
        extensions: 'hpp,cpp,ipp,h,c'
        clangFormatVersion: 14
        inplace: True
        #- uses: EndBug/add-and-commit@v9
        #with:
        #author_name: Clang Robot
        #author_email: robot@example.com
        #message: 'Committing clang-format changes'
        #env:
        #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
